stages:
  - test

test:
  tags: 
    - sandbox
  stage: test
  script: 
    - env
    - whoami
    - pwd
    - ls -la
    - cd $CI_PROJECT_DIR
    - echo $CI_PROJECT_DIR
    - git status
    - git log --oneline
    - echo 'Adding upstream remote \:' $GIT_REMOTE_URL
    - echo "Fetching changes from upstream..."
    - |
        # This needs to be checked
        git fetch upstream --prune;
        echo "Merging upstream changes into local branches...";
        # Get the list of all branches from upstream (excluding HEAD -> references)
        for remote_branch in $(git branch -r | grep -E '^ *upstream/' | grep -v '\->'); do
          # Extract branch name (skip 'upstream/' prefix)
          branch_name="${remote_branch#upstream/}";

          # Checkout/create local branch
          if git rev-parse --verify "$branch_name" &>/dev/null; then
            git checkout "$branch_name";
          else
            git checkout -b "$branch_name" "upstream/$branch_name";
          fi

          # Merge upstream branch
          git merge --no-edit "upstream/$branch_name" || true
        done

        git log --oneline;

        # Optionally push all branches/tags to GitLab
        echo "Pushing merged branches/tags to GitLab...";
        git push origin --all;
        git push origin --tags;