stages:
  - test

test:
  tags: 
    - sandbox
  stage: test
  script: 
    - env
    - whoami
    - pwd
    - ls -la
    - cd $CI_PROJECT_DIR
    - echo $CI_PROJECT_DIR
    - git status
    - git log --oneline